//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebb01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nota_evolucion
    {
        public int nota_evolucion_id { get; set; }
        public string nota { get; set; }
        public Nullable<System.DateTime> fecha_evolucion { get; set; }
        public Nullable<int> tratamiento_id { get; set; }
    
        public virtual tratamiento tratamiento { get; set; }
    }
}
