//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebb01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservacion
    {
        public int reservacion_id { get; set; }
        public System.DateTime fecha_reservacion { get; set; }
        public Nullable<int> paciente_id { get; set; }
    
        public virtual paciente paciente { get; set; }
    }
}
