//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebb01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tratamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tratamiento()
        {
            this.nota_evolucion = new HashSet<nota_evolucion>();
        }
    
        public int tratamiento_id { get; set; }
        public string diagnostico { get; set; }
        public string tratamiento1 { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<int> paciente_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nota_evolucion> nota_evolucion { get; set; }
        public virtual paciente paciente { get; set; }
    }
}
